//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uwitter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uwitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   table {
        ///  font-family: sans-serif;
        ///  font-size: 9.5pt;
        ///  line-height: 1.4;
        ///  border-collapse: collapse;
        ///  border-spacing: 0;
        ///  padding-top: 0;
        ///  margin-top: 0;
        ///}
        ///
        ///tr.hover {
        ///  background-color: #c0c0c0;
        ///}
        ///
        ///td {
        ///  border-bottom: 1px #606060 solid;
        ///  vertical-align: top;
        ///  padding: 4px 0px 4px 0px;
        ///}
        ///
        ///a img {
        ///  border: none;
        ///  width: 24px;
        ///  height: 24px;
        ///  margin-right: 4px;
        ///}
        ///
        ///a {
        ///  text-decoration: none;
        ///}
        ///a:hover {
        ///  text-decoration: underline;
        ///}
        ///
        ///.name {
        ///  font-weight:  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///window.onload = function() {
        ///  if (document.getElementsByTagName) {
        ///    var className = &apos;hover&apos;;
        ///    var t = document.getElementById(&quot;Table&quot;);
        ///    var rows = t.getElementsByTagName(&quot;tr&quot;);
        ///    for (var i = 0; i &lt;rows.length; i++) {
        ///      if (rows[i].className) {
        ///        rows[i].BaseName = rows[i].className;
        ///        rows[i].onmouseover = function(){this.className = className;}
        ///        rows[i].onmouseout = function(){this.className = this.BaseName;}
        ///      }
        ///	}
        ///  }
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string js {
            get {
                return ResourceManager.GetString("js", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon notify {
            get {
                object obj = ResourceManager.GetObject("notify", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
